repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.6.0
  hooks:
  - id: reorder-python-imports
    args: ['--py37-plus']
- repo: https://github.com/python/black
  rev: 19.3b0
  hooks:
  - id: black
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.7
  hooks:
  - id: flake8
